Request {
  params: {},
  raw: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: [Object],
        encoding: 'utf8' },
     readable: false,
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 2725,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [Object],
        _peername: [Object],
        [Symbol(asyncId)]: 55,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 57,
        [Symbol(triggerAsyncId)]: 55 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 2725,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [Object],
        _peername: [Object],
        [Symbol(asyncId)]: 55,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 57,
        [Symbol(triggerAsyncId)]: 55 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'content-type': 'application/json',
        'cache-control': 'no-cache',
        'postman-token': '01516103-121b-4de8-b527-385ff9b3ec02',
        'user-agent': 'PostmanRuntime/7.4.0',
        accept: '*/*',
        host: 'localhost:3000',
        'accept-encoding': 'gzip, deflate',
        'content-length': '47',
        connection: 'keep-alive' },
     rawHeaders: 
      [ 'Content-Type',
        'application/json',
        'cache-control',
        'no-cache',
        'Postman-Token',
        '01516103-121b-4de8-b527-385ff9b3ec02',
        'User-Agent',
        'PostmanRuntime/7.4.0',
        'Accept',
        '*/*',
        'Host',
        'localhost:3000',
        'accept-encoding',
        'gzip, deflate',
        'content-length',
        '47',
        'Connection',
        'keep-alive' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '/api/auth/login',
     method: 'POST',
     statusCode: null,
     statusMessage: null,
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 2725,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [Object],
        _peername: [Object],
        [Symbol(asyncId)]: 55,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 57,
        [Symbol(triggerAsyncId)]: 55 },
     _consuming: true,
     _dumped: false,
     id: 1,
     ip: '127.0.0.1',
     hostname: 'localhost:3000',
     log: { child: [Function] },
     originalUrl: '/api/auth/login',
     read: [Function] },
  query: {},
  headers: 
   { 'content-type': 'application/json',
     'cache-control': 'no-cache',
     'postman-token': '01516103-121b-4de8-b527-385ff9b3ec02',
     'user-agent': 'PostmanRuntime/7.4.0',
     accept: '*/*',
     host: 'localhost:3000',
     'accept-encoding': 'gzip, deflate',
     'content-length': '47',
     connection: 'keep-alive' },
  log: { child: [Function] },
  body: { username: 'saurabh', password: '1234' } }